import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "../components/Providers";
import { cn } from "@/lib/utils";
import { Navbar } from "../components/Navbar";
import { currentUser } from "@clerk/nextjs/server";
import { SessionNavbar } from "../components/SessionNavbar";

const switzer = localFont({
  src: "../../public/fonts/Switzer-Variable.woff2",
  variable: "--font-switzer",
  weight: "100 900",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  

  return (
    <html lang="en">
      <body className={cn(switzer.className, "antialiased overflow-x-clip")}>
        <Providers>
          {!user ? <Navbar /> : <SessionNavbar />}
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
